// File generated by MineTweakerRecipeMaker
//                     READ THIS HEADER BEFORE EDITING ANYTHING
// ================================================================================
//     This file is read and changed by the mod.
//     If you remove/edit any of the markers, IT WILL STOP WORKING!
//     If you want to make manual edits, make a backup of this file!
//     Markers look like this: "//#MARKER something"
//     They indicate where calls should be placed, so that MineTweaker does them in the correct order.
//     Removes come first, then stuff is added.
// ================================================================================
//

// ================================================================================
//#MARKER REMOVE
recipes.remove(<TConstruct:LavaTank>);
recipes.remove(<IC2:plasmaLauncher:1>);
recipes.remove(<TConstruct:explosive.slime>);
recipes.remove(<TConstruct:explosive.slime:2>);
recipes.remove(<Railcraft:machine.alpha>);
recipes.remove(<Railcraft:machine.alpha:2>);
recipes.remove(<IC2:blockMachine:15>);
recipes.remove(<BambooMod:firecracker>);
recipes.remove(<BambooMod:firecracker:1>);
recipes.remove(<BambooMod:firecracker:2>);
recipes.remove(<Botania:laputaShard>);
recipes.remove(<Botania:laputaShard:4>);
recipes.remove(<Botania:laputaShard:9>);
recipes.remove(<Botania:laputaShard:14>);
recipes.remove(<Botania:laputaShard:19>);
recipes.remove(<IC2:blockNuke>);
recipes.remove(<IC2:blockNuke> * 64);
recipes.remove(<flansmod:gunBox.modernweapons>);

// ================================================================================
//#MARKER REMOVE SHAPELESS

// ================================================================================
//#MARKER REMOVE SHAPED

// ================================================================================
//#MARKER ADD

// ================================================================================
//#MARKER ADD SHAPELESS

// ================================================================================
//#MARKER ADD SHAPED

